export const FETCH_PROFILES = 'profiles/FETCH_PROFILES'
export const UPDATE_PROFILELIST = 'profiles/UPDATE_PROFILELIST'
export const FETCH_SKILLS = 'skills/FETCH_SKILLS'
export const UPDATE_SKILLLIST = 'skills/UPDATE_SKILLLIST'
export const SET_LOADING = 'SET_LOADING'
