export const FETCH_PROFILES = 'profiles/FETCH_PROFILES'
export const UPDATE_PROFILE = 'profiles/UPDATE_PROFILE'
export const FETCH_PROFILESKILLS = 'profiles/FETCH_PROFILESKILLS'
export const FETCH_SKILLS = 'skills/FETCH_SKILLS'
export const SET_LOADING = 'SET_LOADING'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
